"""initial_schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-04-19 11:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('pattern_name', sa.Text(), nullable=False),
    sa.Column('techniques', sa.Text(), server_default='[]', nullable=False),
    sa.Column('backends', sa.Text(), server_default='[]', nullable=False),
    sa.Column('detected_at', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('technique_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('backend_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), server_default='{}', nullable=False),
    sa.Column('detected_at', sa.Text(), nullable=False),
    sa.Column('visual_effect', sa.Text(), server_default='', nullable=False),
    sa.Column('visual_intensity', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('remediation', sa.Text(), server_default='[]', nullable=False),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threat_events')
    op.drop_table('correlation_events')
    # ### end Alembic commands ###

